from enum import Enum
from pydantic import BaseModel, Field


class Channel(str, Enum):
    """Input channel — determines output behaviour in the pipeline."""
    TWILIO = "twilio"         # voice call → TTS output
    TEXT_API = "text_api"     # REST /query → SSE / JSON output
    WEBSOCKET = "websocket"   # future: browser widget


class LLMProvider(str, Enum):
    """
    LLM provider enum.
    v1: groq only.
    v2+: swap in ragflow / pgvector / llamaindex without touching callers.
    The pipeline reads payload.llm_provider to route — add a new branch here
    when a new provider is ready. No other file needs to change.
    """
    GROQ = "groq"
    RAGFLOW = "ragflow"       # Phase 4 — not yet implemented
    PGVECTOR = "pgvector"     # Phase 4 — not yet implemented


class QueryPayload(BaseModel):
    """
    Shared input model for the LLM pipeline.

    Both entry points produce this before calling stream_llm_sentences():
        - Voice path: built in ws/call_handler.py from SessionState after STT
        - REST path:  built in routers/query.py from TextQueryRequest

    The pipeline (pipeline/llm.py) only ever sees QueryPayload — it never
    knows whether the input came from a phone call or a REST request.
    This is the abstraction that makes the shared foundation work.

    RAG swap point:
        payload.llm_provider controls which backend handles the query.
        Change agent_config["llm_provider"] = "ragflow" in the agents table
        and pipeline/llm.py will route to the RAG backend automatically.
        No other code changes needed.
    """

    # ── Required ────────────────────────────────────────────────────────────
    agent_id: str = Field(..., description="Agent UUID from agents table")
    text: str = Field(..., description="User message — from STT or direct input")

    # ── Channel ─────────────────────────────────────────────────────────────
    channel: Channel = Field(
        default=Channel.TEXT_API,
        description="Input channel — twilio or text_api",
    )

    # ── Agent context ────────────────────────────────────────────────────────
    agent_config: dict = Field(
        default_factory=dict,
        description=(
            "Full agents row. Keys used by pipeline: "
            "system_prompt, llm_provider, llm_model, tts_voice, workspace_id"
        ),
    )
    kb_documents: list[str] = Field(
        default_factory=list,
        description="Raw text of all KB docs attached to this agent (full-context v1)",
    )

    # ── LLM routing ─────────────────────────────────────────────────────────
    llm_provider: LLMProvider = Field(
        default=LLMProvider.GROQ,
        description=(
            "Which LLM backend to use. Defaults to groq. "
            "Overridden by agent_config['llm_provider'] in pipeline/llm.py. "
            "Set to ragflow/pgvector when Phase 4 RAG is ready — no other changes needed."
        ),
    )

    # ── Conversation context ─────────────────────────────────────────────────
    conversation_history: list[dict[str, str]] = Field(
        default_factory=list,
        description="Prior turns this session: [{role, content}, ...]",
    )
    caller_history: list[dict] = Field(
        default_factory=list,
        description="Past conversation summaries for this caller (from Supabase)",
    )

    # ── Identifiers ──────────────────────────────────────────────────────────
    call_sid: str | None = Field(
        default=None,
        description="Twilio CallSid. Present on twilio channel, None on text_api.",
    )
    conversation_id: str | None = Field(
        default=None,
        description="conversations.id — set when continuing an existing conversation",
    )
    caller_id: str | None = Field(
        default=None,
        description="callers.id in Supabase",
    )
    visitor_id: str | None = Field(
        default=None,
        description=(
            "Optional visitor identifier for external chatbot continuity. "
            "Generated by the widget (e.g. UUID in localStorage). "
            "Used to load visitor history across sessions on the same browser."
        ),
    )


class TextQueryRequest(BaseModel):
    """
    Request body for POST /query (REST text endpoint).
    Validated by FastAPI before the handler runs.

    Used by both:
        - Dashboard chat (JWT auth, no visitor_id needed)
        - External chatbot widget (API key auth, visitor_id optional)
    """
    agent_id: str = Field(..., description="Agent UUID")
    text: str = Field(..., min_length=1, description="User's message text")
    conversation_id: str | None = Field(
        default=None,
        description=(
            "Pass the conversation_id returned by a previous /query response "
            "to continue a stateful conversation. Omit to start a new one."
        ),
    )
    stream: bool = Field(
        default=True,
        description="True → SSE streaming. False → single JSON response.",
    )
    visitor_id: str | None = Field(
        default=None,
        description=(
            "Optional. For external chatbot widgets: a stable ID for this visitor "
            "(e.g. UUID stored in localStorage). Enables conversation history across "
            "sessions on the same browser. Not needed for dashboard chat."
        ),
    )


class TextQueryResponse(BaseModel):
    """
    Response body for POST /query with stream=false.
    """
    text: str
    conversation_id: str
    agent_id: str